//
// Created by moroshma on 11.11.23.
//

#ifndef SYNTACTICAL_ANALYZER_HANDLER_H
#define SYNTACTICAL_ANALYZER_HANDLER_H

enum ERROR {
  MALLOC_ERROR = 1,
  READFILE_ERROR = 2,
  PARSE_ERROR = 3,
  READ_FLAG_ERROR = 4,
  UNKNOWN_ERROR = 5,
  OPEN_FILE_ERROR = 6,
  SUCCESS = 0
};

class handler {};

#endif // SYNTACTICAL_ANALYZER_HANDLER_H
